// Comprehensive list of parrot species commonly kept as pets, organized by family.
// Swedish common names first, scientific name in parentheses where relevant.
// Used by /registrera-fagel and /rapportera-bortflygen.

export const PARROT_SPECIES = [
    {
        family: "Ara (Macaws)",
        items: [
            "Ara – Blå och gul (Ara ararauna)",
            "Ara – Grönvingad (Ara chloropterus)",
            "Ara – Röd / Scarlet (Ara macao)",
            "Ara – Hyacint (Anodorhynchus hyacinthinus)",
            "Ara – Militär (Ara militaris)",
            "Ara – Buffonara / Storgrön (Ara ambiguus)",
            "Ara – Härlig (Ara rubrogenys)",
            "Ara – Svavelbröst (Ara couloni)",
            "Dvärgara – Kastanjefrontad (Ara severus)",
            "Dvärgara – Blåpannad (Primolius couloni)",
            "Dvärgara – Illigers (Primolius maracana)",
            "Dvärgara – Halsband / Yellow-collared (Primolius auricollis)",
            "Dvärgara – Rödaxlad / Hahns (Diopsittaca nobilis)",
            "Catalinaara (hybrid)",
            "Camelotaara (hybrid)",
            "Harlequinaara (hybrid)",
        ],
    },
    {
        family: "Amazoner (Amazon parrots)",
        items: [
            "Amazon – Dubbelgul (Amazona oratrix)",
            "Amazon – Gulnackad (Amazona auropalliata)",
            "Amazon – Gulkindad (Amazona autumnalis)",
            "Amazon – Blåpannad / Turkos (Amazona aestiva)",
            "Amazon – Orangevingad (Amazona amazonica)",
            "Amazon – Mjölig (Amazona farinosa)",
            "Amazon – Mealy / Grönkindad (Amazona farinosa guatemalae)",
            "Amazon – Kubansk (Amazona leucocephala)",
            "Amazon – Rödpannad (Amazona rhodocorytha)",
            "Amazon – Vitpannad (Amazona albifrons)",
            "Amazon – Panama (Amazona ochrocephala panamensis)",
            "Amazon – Lilacine (Amazona lilacina)",
            "Amazon – Festivo (Amazona festiva)",
            "Amazon – Vinaceous (Amazona vinacea)",
            "Amazon – Puerto Rico (Amazona vittata)",
        ],
    },
    {
        family: "Kakaduor (Cockatoos)",
        items: [
            "Kakadu – Vit / Alba (Cacatua alba)",
            "Kakadu – Molukk / Salmon (Cacatua moluccensis)",
            "Kakadu – Gulhättad större (Cacatua galerita)",
            "Kakadu – Gulhättad mindre (Cacatua sulphurea)",
            "Kakadu – Citron (Cacatua sulphurea citrinocristata)",
            "Kakadu – Rosa / Galah (Eolophus roseicapilla)",
            "Kakadu – Röshuvad (Cacatua goffiniana)",
            "Kakadu – Ducorps (Cacatua ducorpsii)",
            "Kakadu – Ceylonbara / Baudins (Zanda baudinii)",
            "Kakadu – Palm (Probosciger aterrimus)",
            "Kakadu – Svart / Röd-tailed (Calyptorhynchus banksii)",
            "Kakadu – Major Mitchell / Leadbeaters (Lophochroa leadbeateri)",
            "Kakadu – Filippinsk (Cacatua haematuropygia)",
        ],
    },
    {
        family: "Grå papegojor (African Greys)",
        items: [
            "Grå papegoja – Kongo (Psittacus erithacus)",
            "Grå papegoja – Timneh (Psittacus timneh)",
        ],
    },
    {
        family: "Eclectus",
        items: [
            "Eclectus – Salomonöarnas (Eclectus roratus solomonensis)",
            "Eclectus – Vosmaeri (Eclectus roratus vosmaeri)",
            "Eclectus – Grand (Eclectus roratus roratus)",
            "Eclectus – Röd-sided (Eclectus roratus polychloros)",
        ],
    },
    {
        family: "Conurer (Conures)",
        items: [
            "Conure – Sol / Sun (Aratinga solstitialis)",
            "Conure – Jenday (Aratinga jandaya)",
            "Conure – Solstice (Aratinga solstitialis mutation)",
            "Conure – Gulaxlad (Aratinga nana)",
            "Conure – Nanday / Svarthövdad (Aratinga nenday)",
            "Conure – Grönkindad (Pyrrhura molinae)",
            "Conure – Pearly (Pyrrhura lepida)",
            "Conure – Fireys (Pyrrhura fireys)",
            "Conure – Blåkronad (Thectocercus acuticaudatus)",
            "Conure – Vittipes (Psittacara leucophthalmus)",
            "Conure – Mitred (Psittacara mitratus)",
            "Conure – Dusky / Weddells (Aratinga weddellii)",
            "Conure – Röstpannad (Aratinga wagleri)",
            "Conure – Half-moon (Eupsittula canicularis)",
            "Conure – Peach-fronted (Eupsittula aurea)",
            "Conure – Painted (Pyrrhura picta)",
            "Conure – Crimson-bellied (Pyrrhura perlata)",
            "Conure – Patagonian (Cyanoliseus patagonus)",
            "Conure – Golden / Queen of Bavaria (Guaruba guarouba)",
        ],
    },
    {
        family: "Lori / Lorikeet",
        items: [
            "Lori – Regnbågslorikeet (Trichoglossus moluccanus)",
            "Lori – Rödbrödad (Trichoglossus rubritorquis)",
            "Lori – Svarthuvad (Lorius lory)",
            "Lori – Chattering (Lorius garrulus)",
            "Lori – Duskyorange (Pseudeos fuscata)",
            "Lori – Röd / Moluccan (Eos bornea)",
            "Lori – Iris (Psitteuteles iris)",
            "Lori – Fjällbröst (Trichoglossus chlorolepidotus)",
            "Lori – Yellow-bibbed (Lorius chlorocercus)",
            "Lori – Purple-naped (Lorius domicella)",
            "Lori – Ornate (Trichoglossus ornatus)",
        ],
    },
    {
        family: "Poicephalus (Afrikanska tigger-papegojor)",
        items: [
            "Senegal-papegoja (Poicephalus senegalus)",
            "Meyers papegoja (Poicephalus meyeri)",
            "Rödbukad papegoja (Poicephalus rufiventris)",
            "Kap papegoja (Poicephalus robustus)",
            "Jardines papegoja (Poicephalus gulielmi)",
            "Rüppels papegoja (Poicephalus rueppellii)",
            "Brunhuvad papegoja (Poicephalus cryptoxanthus)",
        ],
    },
    {
        family: "Pionus",
        items: [
            "Pionus – Blåhuvad (Pionus menstruus)",
            "Pionus – Vithuvad (Pionus senilis)",
            "Pionus – Bronshuvad / Bronze-winged (Pionus chalcopterus)",
            "Pionus – Duskys (Pionus fuscus)",
            "Pionus – Maximilian (Pionus maximiliani)",
            "Pionus – Plum-crowned (Pionus tumultuosus)",
        ],
    },
    {
        family: "Caiques",
        items: [
            "Caique – Vitbukig (Pionites leucogaster)",
            "Caique – Svartbukig (Pionites melanocephalus)",
        ],
    },
    {
        family: "Ringnecks & Alexandriner",
        items: [
            "Ringneck – Indisk (Psittacula krameri manillensis)",
            "Ringneck – Afrikansk (Psittacula krameri krameri)",
            "Alexanderpapegoja (Psittacula eupatria)",
            "Plumhuvad parakit (Psittacula cyanocephala)",
            "Malabar parakit (Psittacula columboides)",
            "Långstjärt parakit / Derbyan (Psittacula derbiana)",
            "Slaty-headed parakit (Psittacula himalayana)",
            "Mustaschparakit (Psittacula alexandri)",
            "Blossom-headed parakit (Psittacula roseata)",
        ],
    },
    {
        family: "Dvärgpapegojor (Lovebirds)",
        items: [
            "Dvärgpapegoja – Fischer (Agapornis fischeri)",
            "Dvärgpapegoja – Persika / Peach-faced (Agapornis roseicollis)",
            "Dvärgpapegoja – Svartkindad (Agapornis nigrigenis)",
            "Dvärgpapegoja – Masked (Agapornis personatus)",
            "Dvärgpapegoja – Lilian's / Nyasa (Agapornis lilianae)",
            "Dvärgpapegoja – Röd-faced (Agapornis pullarius)",
            "Dvärgpapegoja – Madagaskar / Grå-headed (Agapornis canus)",
            "Dvärgpapegoja – Abessinian (Agapornis taranta)",
            "Dvärgpapegoja – Svart-collared (Agapornis swindernianus)",
        ],
    },
    {
        family: "Quaker / Munkparakit",
        items: [
            "Quaker / Munkparakit (Myiopsitta monachus)",
            "Quaker – Blå mutation",
            "Quaker – Gul (lutino)",
            "Quaker – Cinnamon",
        ],
    },
    {
        family: "Australiska parakiter",
        items: [
            "Nymfkakadu / Cockatiel (Nymphicus hollandicus)",
            "Undulat / Budgie (Melopsittacus undulatus)",
            "Bourkes parakit (Neopsephotus bourkii)",
            "Turquoisine parakit (Neophema pulchella)",
            "Elegant parakit (Neophema elegans)",
            "Splendid / Scarlet-chested parakit (Neophema splendida)",
            "Rock parrot (Neophema petrophila)",
            "Röd-rumped parakit (Psephotus haematonotus)",
            "Rosella – Blå (Platycercus adscitus)",
            "Rosella – Röd (Platycercus elegans)",
            "Rosella – Gul (Platycercus flaveolus)",
            "Rosella – Östlig (Platycercus eximius)",
            "Rosella – Västlig (Platycercus icterotis)",
            "Kungsparakit (Alisterus scapularis)",
            "Barnards parakit (Barnardius zonarius barnardi)",
            "Regent parrot (Polytelis anthopeplus)",
            "Prinsess Alexandra parakit (Polytelis alexandrae)",
            "Superb parrot (Polytelis swainsonii)",
        ],
    },
    {
        family: "Övriga",
        items: [
            "Kakariki – Röd (Cyanoramphus novaezelandiae)",
            "Kakariki – Gul (Cyanoramphus auriceps)",
            "Kea (Nestor notabilis)",
            "Kaka (Nestor meridionalis)",
            "Vasa-papegoja större (Coracopsis vasa)",
            "Vasa-papegoja mindre (Coracopsis nigra)",
            "Blåpannad hängpapegoja (Loriculus galgulus)",
            "Sparv-papegoja – Grön-rumped (Forpus passerinus)",
            "Sparv-papegoja – Pacific / Celestial (Forpus coelestis)",
            "Sparv-papegoja – Blåvingad (Forpus xanthopterygius)",
            "Sparv-papegoja – Mexikansk (Forpus cyanopygius)",
            "Sparv-papegoja – Spectacled (Forpus conspicillatus)",
            "Hyacint hyacintara (Anodorhynchus hyacinthinus)",
        ],
    },
    {
        family: "Annat",
        items: [
            "Annat / Ej i listan (specificera i beskrivning)",
        ],
    },
];

// Flat list of all species for search/matching
export const ALL_SPECIES = PARROT_SPECIES.flatMap((g) =>
    g.items.map((s) => ({ value: s, family: g.family })),
);
